[[profile]]
name = "home"

[[profile.output]]
enable = true
search = ["m=LG ULTRAGEAR+", "s=401NTZN3M765", "v=LG Electronics"]
mode = "3840x2160@144.05Hz"
position = "0,0"
scale = 1.3
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = false
search = ["m=0x1403", "s=", "v=California Institute of Technology"]

[[profile]]
name = "laptop"

[[profile.output]]
enable = true
search = ["m=0x1403", "s=", "v=California Institute of Technology"]
mode = "3840x2400@60Hz"
position = "0,0"
scale = 1.75
transform = "normal"
adaptive_sync = false

