#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Including custom zsh completions. This must run
# BEFORE we init zprezto.
fpath+="${ZDOTDIR:-$HOME}/contrib/completions"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Adding ~/.local/bin to the list of $PATH
typeset -U path
path=(${ZDOTDIR:-$HOME}/.local/bin $path)
export PATH

