#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Including custom zsh completions. This must run
# BEFORE we init zprezto.
fpath+="${ZDOTDIR:-$HOME}/contrib/completions"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Adding ~/.local/bin to the list of $PATH
typeset -U path
path=(${ZDOTDIR:-$HOME}/.local/bin $path)
export PATH

# Adding nvm to the list of path.
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

