#theme = "gruvbox_dark_hard"
theme = "dark_plus"

[editor]
line-number = "relative"
cursorline = true
cursorcolumn = false
#text-width = 88

[editor.cursor-shape]
insert = "bar"
normal = "block"
#select = "underline"

[editor.file-picker]
hidden = true
